/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ehrickwilliam.gui;

import br.com.ehrickwilliam.bibliotecas.Leitor;
import br.com.ehrickwilliam.conexao.HibernateConfiguration;
import br.com.ehrickwilliam.conexao.TransactionManager;
import br.com.ehrickwilliam.daos.DaoUsuario;
import br.com.ehrickwilliam.model.Conta;
import br.com.ehrickwilliam.model.Usuario;
import java.awt.Cursor;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import org.eclipse.jgit.api.errors.GitAPIException;

/**
 *
 * @author Erick
 */
public class JDialogImportantoUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCadastroClienteFisico
     *
     * @param parent
     * @param modal
     */
    private final Leitor leitor;

    public JDialogImportantoUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButtonExecutar.setVisible(false);
        leitor = new Leitor();
        jProgressBar.setIndeterminate(true);
        this.setTitle("Importando usuários...");
        executar(jButtonExecutar, leitor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelstatus = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        jButtonExecutar = new javax.swing.JButton();
        jLabelstatus1 = new javax.swing.JLabel();
        jLabelEtapa = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(443, 185));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelstatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelstatus.setText("Processo iniciado!");
        getContentPane().add(jLabelstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        getContentPane().add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 380, 20));

        jButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabelstatus1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelstatus1.setText("Por favor, aguarde...");
        getContentPane().add(jLabelstatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        getContentPane().add(jLabelEtapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarActionPerformed
        retornoConsulta();
        this.dispose();
    }//GEN-LAST:event_jButtonExecutarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JLabel jLabelEtapa;
    private javax.swing.JLabel jLabelstatus;
    private javax.swing.JLabel jLabelstatus1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void retornoConsulta() {
        try {
            leitor.listarUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(JDialogImportantoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JDialogImportantoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (GitAPIException ex) {
            Logger.getLogger(JDialogImportantoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jProgressBar.setIndeterminate(false);
        jProgressBar.setMaximum(leitor.getEmails().size());
        jProgressBar.setStringPainted(true);
        jProgressBar.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        HibernateConfiguration.setBase("minerador");
        for (String email : leitor.getEmails()) {
            Conta conta = new Conta(email, null);
            Usuario usuario = new Usuario();
            usuario.setConta(conta);
            TransactionManager.beginTransaction();

            new DaoUsuario().persistir(usuario);
            TransactionManager.commit();
            jLabelstatus.setText("Inserindo " + email + " ");
            jProgressBar.setValue(jProgressBar.getValue() + 1);
        }
    }

    public static void executar(final JButton botao, final Leitor leitor) {
        new Thread() {
            @Override
            public void run() {
                int flag = 0;
                while (flag == 0) {

                    try {
                        botao.doClick();
                        flag = +1;

                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        }.start();

    }
}
